const state = {
  mainPage: {},
  topicOptions: [
    { name: "Topic", value: "0" },
    { name: "Politic", value: "1" },
    { name: "Art", value: "2" },
    { name: "Culture", value: "3" },
    { name: "Economic", value: "4" },
    { name: "Something...", value: "5" },
  ],
  weekOptions: [
    { name: "This Day", value: "0" },
    { name: "This Week", value: "1" },
    { name: "This Month", value: "2" },
    { name: "This Quarter", value: "3" },
    { name: "This Year", value: "4" },
  ],
  cardList: [
    {
      name: "Connection trust1",
      src: Img1,
      value: "0",
      state: true,
      count: 214,
    },
    {
      name: "Connection trust2",
      src: Img2,
      value: "1",
      state: false,
      count: 29,
    },
    {
      name: "Connection trust3",
      src: Img3,
      value: "2",
      state: true,
      count: 232,
    },
    {
      name: "Connection trust4",
      src: Img4,
      value: "3",
      state: true,
      count: 80,
    },
    {
      name: "Connection trust5",
      src: Img5,
      value: "4",
      state: false,
      count: 212,
    },
    {
      name: "Connection trust6",
      src: Img6,
      value: "5",
      state: true,
      count: 298,
    },
    {
      name: "Connection trust7",
      src: Img7,
      value: "6",
      state: true,
      count: 264,
    },
    {
      name: "Connection trust8",
      src: Img8,
      value: "7",
      state: true,
      count: 173,
    },
    {
      name: "Connection trust9",
      src: Img9,
      value: "8",
      state: false,
      count: 129,
    },
    {
      name: "Connection trust10",
      src: Img10,
      value: "9",
      state: true,
      count: 109,
    },
    {
      name: "Connection trust11",
      src: Img1,
      value: "10",
      state: false,
      count: 163,
    },
    {
      name: "Connection trust12",
      src: Img2,
      value: "11",
      state: true,
      count: 154,
    },
  ],
  artPosts: [
    {
      h1: "Explain to you",
      text: "But I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system, and expound the actual teachings of the great explorer of the truth, the master-builder of human happiness. But I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system, and expound the actual teachings of the great explorer of the truth, the master-builder of human happiness.",
      src: PostImg1,
      date: "Sep 15",
      bred: "11 min read",
      value: "0",
      state: true,
      count: 13,
    },
    {
      h1: "Brat, no ne drug",
      text: "Mac Studio is an entirely new Mac desktop. And it all starts with your choice of the ferociously fast M1 Max or the all-new M1 Ultra — the most powerful chip ever in a personal computer.",
      src: PostImg2,
      date: "Mar 02",
      bred: "34 min read",
      value: "1",
      state: true,
      count: 56,
    },
    {
      h1: "Drug, no ne SWAT",
      text: "Simply good people",
      src: PostImg3,
      date: "Jan 21",
      bred: "2 min read",
      value: "2",
      state: false,
      count: 95,
    },
    {
      h1: "Explain to you",
      text: "But I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system, and expound the actual teachings of the great explorer of the truth, the master-builder of human happiness. But I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system, and expound the actual teachings of the great explorer of the truth, the master-builder of human happiness.",
      src: PostImg1,
      date: "Sep 15",
      bred: "11 min read",
      value: "3",
      state: true,
      count: 147,
    },
    {
      h1: "Explain to youu",
      text: "But I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system, and expound the actual teachings of the great explorer of the truth, the master-builder of human happiness. But I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system, and expound the actual teachings of the great explorer of the truth, the master-builder of human happiness.",
      src: PostImg1,
      date: "Sep 15",
      bred: "11 min read",
      value: "4",
      state: true,
      count: 112,
    },
  ],
  creatorsToFollow: [
    {
      name: "Harley Spector",
      text: "The master-builder of human happiness...",
      src: AvatarImg2,
      value: "0",
      state: true,
    },
    {
      name: "Lashped Volfovich",
      text: "The master-durilder of human society...",
      src: AvatarImg3,
      value: "1",
      state: false,
    },
    {
      name: "Harley Devidson",
      text: "The master-chef of motor happiness...",
      src: AvatarImg2,
      value: "2",
      state: true,
    },
    {
      name: "James May",
      text: "The of(f) human ...",
      src: AvatarImg2,
      value: "3",
      state: false,
    },
    {
      name: "Kirill Maskim",
      text: "Laster-bodibilder of numeric dignaty...",
      src: AvatarImg3,
      value: "4",
      state: true,
    },
  ],
};

export default state;

// const topicOptions = [
//   { name: "Topic", value: "0" },
//   { name: "Politic", value: "1" },
//   { name: "Art", value: "2" },
//   { name: "Culture", value: "3" },
//   { name: "Economic", value: "4" },
//   { name: "Something...", value: "5" },
// ];

// const weekOptions = [
//   { name: "This Day", value: "0" },
//   { name: "This Week", value: "1" },
//   { name: "This Month", value: "2" },
//   { name: "This Quarter", value: "3" },
//   { name: "This Year", value: "4" },
// ];
// const cardList = [
//   {
//     name: "Connection trust1",
//     src: Img1,
//     value: "0",
//     state: true,
//     count: 214,
//   },
//   {
//     name: "Connection trust2",
//     src: Img2,
//     value: "1",
//     state: false,
//     count: 29,
//   },
//   {
//     name: "Connection trust3",
//     src: Img3,
//     value: "2",
//     state: true,
//     count: 232,
//   },
//   {
//     name: "Connection trust4",
//     src: Img4,
//     value: "3",
//     state: true,
//     count: 80,
//   },
//   {
//     name: "Connection trust5",
//     src: Img5,
//     value: "4",
//     state: false,
//     count: 212,
//   },
//   {
//     name: "Connection trust6",
//     src: Img6,
//     value: "5",
//     state: true,
//     count: 298,
//   },
//   {
//     name: "Connection trust7",
//     src: Img7,
//     value: "6",
//     state: true,
//     count: 264,
//   },
//   {
//     name: "Connection trust8",
//     src: Img8,
//     value: "7",
//     state: true,
//     count: 173,
//   },
//   {
//     name: "Connection trust9",
//     src: Img9,
//     value: "8",
//     state: false,
//     count: 129,
//   },
//   {
//     name: "Connection trust10",
//     src: Img10,
//     value: "9",
//     state: true,
//     count: 109,
//   },
//   {
//     name: "Connection trust11",
//     src: Img1,
//     value: "10",
//     state: false,
//     count: 163,
//   },
//   {
//     name: "Connection trust12",
//     src: Img2,
//     value: "11",
//     state: true,
//     count: 154,
//   },
// ];

// const artPosts = [
//   {
//     h1: "Explain to you",
//     text: "But I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system, and expound the actual teachings of the great explorer of the truth, the master-builder of human happiness. But I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system, and expound the actual teachings of the great explorer of the truth, the master-builder of human happiness.",
//     src: PostImg1,
//     date: "Sep 15",
//     bred: "11 min read",
//     value: "0",
//     state: true,
//     count: 13,
//   },
//   {
//     h1: "Brat, no ne drug",
//     text: "Mac Studio is an entirely new Mac desktop. And it all starts with your choice of the ferociously fast M1 Max or the all-new M1 Ultra — the most powerful chip ever in a personal computer.",
//     src: PostImg2,
//     date: "Mar 02",
//     bred: "34 min read",
//     value: "1",
//     state: true,
//     count: 56,
//   },
//   {
//     h1: "Drug, no ne SWAT",
//     text: "Simply good people",
//     src: PostImg3,
//     date: "Jan 21",
//     bred: "2 min read",
//     value: "2",
//     state: false,
//     count: 95,
//   },
//   {
//     h1: "Explain to you",
//     text: "But I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system, and expound the actual teachings of the great explorer of the truth, the master-builder of human happiness. But I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system, and expound the actual teachings of the great explorer of the truth, the master-builder of human happiness.",
//     src: PostImg1,
//     date: "Sep 15",
//     bred: "11 min read",
//     value: "3",
//     state: true,
//     count: 147,
//   },
//   {
//     h1: "Explain to youu",
//     text: "But I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system, and expound the actual teachings of the great explorer of the truth, the master-builder of human happiness. But I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system, and expound the actual teachings of the great explorer of the truth, the master-builder of human happiness.",
//     src: PostImg1,
//     date: "Sep 15",
//     bred: "11 min read",
//     value: "4",
//     state: true,
//     count: 112,
//   },
// ];

// const creatorsToFollow = [
//   {
//     name: "Harley Spector",
//     text: "The master-builder of human happiness...",
//     src: AvatarImg2,
//     value: "0",
//     state: true,
//   },
//   {
//     name: "Lashped Volfovich",
//     text: "The master-durilder of human society...",
//     src: AvatarImg3,
//     value: "1",
//     state: false,
//   },
//   {
//     name: "Harley Devidson",
//     text: "The master-chef of motor happiness...",
//     src: AvatarImg2,
//     value: "2",
//     state: true,
//   },
//   {
//     name: "James May",
//     text: "The of(f) human ...",
//     src: AvatarImg2,
//     value: "3",
//     state: false,
//   },
//   {
//     name: "Kirill Maskim",
//     text: "Laster-bodibilder of numeric dignaty...",
//     src: AvatarImg3,
//     value: "4",
//     state: true,
//   },
// ];
